### ISSUE TITLE
I keep getting thi8s issue when i try to run the trainer.py

### ISSUE THREAD

**Issue by ST2-EV** [Deepest-Project/MelNet#24]
![Screenshot from 2020-02-24 08-45-27](https://user-images.githubusercontent.com/40699517/75126942-3fba6800-56e2-11ea-9c80-0c4c1e1473a9.png)

**Comment by CookiePPP** [comment]
What command did you use?
You'll need to specify the config file you want to use inside your command.
e.g `-c config/kss.yaml`
(disclaimer: I haven't used this repo yet, I just read the code)

**Comment by ST2-EV** [comment]
nvm, i tried voxceleb2 which has not been implemented yet
it is working with blizzard
my bad
